#include <algorithm>
#include <array>
#include <cmath>
#include <limits>
#include <vector>
#include "Raven/Physics/Collision/CollisionDetection.h"
#include "Raven/Physics/Collision/OBB.h"
namespace Raven::ph { namespace {
constexpr float AxisEpsilonSquared=1e-10f,ClipEpsilon=1e-5f;
enum class SATFeatureType{FaceA,FaceB,EdgeEdge};
struct SATResult{bool Intersect=false;float Penetration=std::numeric_limits<float>::max();math::Vec3 Normal{1,0,0};SATFeatureType Feature=SATFeatureType::FaceA;int AxisA=-1,AxisB=-1;};
uint8_t FaceID(int axis,float sign){return static_cast<uint8_t>(axis*2+(sign>0?1:0));}
uint8_t VertexID(const OBB&b,const math::Vec3&p){const math::Vec3 d=p-b.Center;uint8_t id=0;for(int i=0;i<3;++i)if(math::Vec3::Dot(d,b.Axis[i])>=0)id|=static_cast<uint8_t>(1u<<i);return id;}
uint8_t EdgeID(const OBB&b,int axis,const math::Vec3&support){const math::Vec3 d=support-b.Center;uint8_t sides=0,bit=0;for(int i=0;i<3;++i){if(i==axis)continue;if(math::Vec3::Dot(d,b.Axis[i])>=0)sides|=static_cast<uint8_t>(1u<<bit);++bit;}return static_cast<uint8_t>(axis*4+sides);}
void SetCombinedMaterial(const ColliderComponent&a,const ColliderComponent&b,ContactManifold&m){m.Restitution=std::min(std::max(a.Restitution,0.f),std::max(b.Restitution,0.f));m.StaticFriction=std::sqrt(std::max(a.StaticFriction,0.f)*std::max(b.StaticFriction,0.f));m.DynamicFriction=std::sqrt(std::max(a.DynamicFriction,0.f)*std::max(b.DynamicFriction,0.f));m.IsTrigger=a.IsTrigger||b.IsTrigger;}
float ProjectionRadius(const OBB&b,const math::Vec3&a){return std::abs(math::Vec3::Dot(a,b.Axis[0]))*b.HalfExtents.x+std::abs(math::Vec3::Dot(a,b.Axis[1]))*b.HalfExtents.y+std::abs(math::Vec3::Dot(a,b.Axis[2]))*b.HalfExtents.z;}
bool TestAxis(const OBB&a,const OBB&b,const math::Vec3&delta,const math::Vec3&raw,SATFeatureType f,int ia,int ib,SATResult&r){float l=raw.LengthSq();if(l<=AxisEpsilonSquared)return true;math::Vec3 axis=raw/std::sqrt(l);float overlap=ProjectionRadius(a,axis)+ProjectionRadius(b,axis)-std::abs(math::Vec3::Dot(delta,axis));if(overlap<0)return false;if(overlap<r.Penetration){if(math::Vec3::Dot(delta,axis)<0)axis=-axis;r.Penetration=overlap;r.Normal=axis;r.Feature=f;r.AxisA=ia;r.AxisB=ib;}return true;}
bool ComputeSAT(const OBB&a,const OBB&b,SATResult&r){r=SATResult{};math::Vec3 d=b.Center-a.Center;for(int i=0;i<3;++i)if(!TestAxis(a,b,d,a.Axis[i],SATFeatureType::FaceA,i,-1,r))return false;for(int j=0;j<3;++j)if(!TestAxis(a,b,d,b.Axis[j],SATFeatureType::FaceB,-1,j,r))return false;for(int i=0;i<3;++i)for(int j=0;j<3;++j)if(!TestAxis(a,b,d,math::Vec3::Cross(a.Axis[i],b.Axis[j]),SATFeatureType::EdgeEdge,i,j,r))return false;r.Intersect=true;return true;}
std::array<math::Vec3,4> GetFaceVertices(const OBB&b,int axis,float sign){int t0=(axis+1)%3,t1=(axis+2)%3;math::Vec3 c=b.Center+b.Axis[axis]*(b.HalfExtents[axis]*sign),u=b.Axis[t0]*b.HalfExtents[t0],v=b.Axis[t1]*b.HalfExtents[t1];return{c-u-v,c+u-v,c+u+v,c-u+v};}
std::vector<math::Vec3> ClipPolygonAgainstPlane(const std::vector<math::Vec3>&in,const math::Vec3&n,float off){std::vector<math::Vec3>out;if(in.empty())return out;math::Vec3 prev=in.back();float pd=math::Vec3::Dot(n,prev)-off;bool pi=pd<=ClipEpsilon;for(const auto&cur:in){float cd=math::Vec3::Dot(n,cur)-off;bool ci=cd<=ClipEpsilon;if(ci!=pi){float den=pd-cd;if(std::abs(den)>1e-8f)out.push_back(prev+(cur-prev)*(pd/den));}if(ci)out.push_back(cur);prev=cur;pd=cd;pi=ci;}return out;}
int FindIncidentFace(const OBB&i,const math::Vec3&n,float&sign){int best=0;float d=std::abs(math::Vec3::Dot(n,i.Axis[0]));for(int a=1;a<3;++a){float c=std::abs(math::Vec3::Dot(n,i.Axis[a]));if(c>d){d=c;best=a;}}sign=math::Vec3::Dot(n,i.Axis[best])>0?-1.f:1.f;return best;}
void GenerateFaceContacts(const OBB&ref,const OBB&inc,int refAxis,const math::Vec3&refNormal,bool referenceIsA,ContactManifold&m){float refSign=math::Vec3::Dot(refNormal,ref.Axis[refAxis])>=0?1.f:-1.f;math::Vec3 fc=ref.Center+ref.Axis[refAxis]*(ref.HalfExtents[refAxis]*refSign);float incSign=1;int incAxis=FindIncidentFace(inc,refNormal,incSign);auto verts=GetFaceVertices(inc,incAxis,incSign);std::vector<math::Vec3>poly(verts.begin(),verts.end());int t0=(refAxis+1)%3,t1=(refAxis+2)%3;math::Vec3 u=ref.Axis[t0],v=ref.Axis[t1];float hu=ref.HalfExtents[t0],hv=ref.HalfExtents[t1];poly=ClipPolygonAgainstPlane(poly,u,math::Vec3::Dot(u,fc)+hu);poly=ClipPolygonAgainstPlane(poly,-u,math::Vec3::Dot(-u,fc)+hu);poly=ClipPolygonAgainstPlane(poly,v,math::Vec3::Dot(v,fc)+hv);poly=ClipPolygonAgainstPlane(poly,-v,math::Vec3::Dot(-v,fc)+hv);for(const auto&vertex:poly){if(m.PointCount>=ContactManifold::MaxContactPointCount)break;float sd=math::Vec3::Dot(refNormal,vertex-fc);if(sd<=ClipEpsilon){ContactPoint p{};p.Penetration=std::max(-sd,0.f);p.Position=vertex-refNormal*(sd*.5f);const uint8_t rf=FaceID(refAxis,refSign),iv=VertexID(inc,vertex);if(referenceIsA){p.Feature.TypeA=ContactFeatureType::Face;p.Feature.IndexA=rf;p.Feature.TypeB=ContactFeatureType::Vertex;p.Feature.IndexB=iv;}else{p.Feature.TypeA=ContactFeatureType::Vertex;p.Feature.IndexA=iv;p.Feature.TypeB=ContactFeatureType::Face;p.Feature.IndexB=rf;}m.AddPoint(p);}}}
void ClosestPointsOnSegments(const math::Vec3&p1,const math::Vec3&q1,const math::Vec3&p2,const math::Vec3&q2,math::Vec3&A,math::Vec3&B){math::Vec3 d1=q1-p1,d2=q2-p2,r=p1-p2;float a=math::Vec3::Dot(d1,d1),e=math::Vec3::Dot(d2,d2),f=math::Vec3::Dot(d2,r),s=0,t=0;if(a<=1e-12f&&e<=1e-12f){A=p1;B=p2;return;}if(a<=1e-12f)t=std::clamp(f/e,0.f,1.f);else{float c=math::Vec3::Dot(d1,r);if(e<=1e-12f)s=std::clamp(-c/a,0.f,1.f);else{float b=math::Vec3::Dot(d1,d2),den=a*e-b*b;if(std::abs(den)>1e-12f)s=std::clamp((b*f-c*e)/den,0.f,1.f);t=(b*s+f)/e;if(t<0){t=0;s=std::clamp(-c/a,0.f,1.f);}else if(t>1){t=1;s=std::clamp((b-c)/a,0.f,1.f);}}}A=p1+d1*s;B=p2+d2*t;}
void GetSupportEdge(const OBB&b,int axis,const math::Vec3&dir,math::Vec3&s,math::Vec3&e){math::Vec3 c=b.Center;for(int i=0;i<3;++i){if(i==axis)continue;float sign=math::Vec3::Dot(dir,b.Axis[i])>=0?1.f:-1.f;c+=b.Axis[i]*(b.HalfExtents[i]*sign);}math::Vec3 ev=b.Axis[axis]*b.HalfExtents[axis];s=c-ev;e=c+ev;}
void GenerateEdgeContact(const OBB&a,const OBB&b,const SATResult&sat,ContactManifold&m){math::Vec3 a0,a1,b0,b1;GetSupportEdge(a,sat.AxisA,sat.Normal,a0,a1);GetSupportEdge(b,sat.AxisB,-sat.Normal,b0,b1);math::Vec3 pa,pb;ClosestPointsOnSegments(a0,a1,b0,b1,pa,pb);ContactPoint p{};p.Position=(pa+pb)*.5f;p.Penetration=sat.Penetration;p.Feature.TypeA=ContactFeatureType::Edge;p.Feature.IndexA=EdgeID(a,sat.AxisA,(a0+a1)*.5f);p.Feature.TypeB=ContactFeatureType::Edge;p.Feature.IndexB=EdgeID(b,sat.AxisB,(b0+b1)*.5f);m.AddPoint(p);}
}
bool GenerateBoxBoxManifold(Entity ea,const TransformComponent&ta,const ColliderComponent&ca,Entity eb,const TransformComponent&tb,const ColliderComponent&cb,ContactManifold&out){OBB a{},b{};if(!ComputeBoxOBB(ta,ca,a)||!ComputeBoxOBB(tb,cb,b))return false;SATResult sat{};if(!ComputeSAT(a,b,sat))return false;out=ContactManifold{};out.A=ea;out.B=eb;out.Normal=sat.Normal;SetCombinedMaterial(ca,cb,out);if(sat.Feature==SATFeatureType::FaceA)GenerateFaceContacts(a,b,sat.AxisA,sat.Normal,true,out);else if(sat.Feature==SATFeatureType::FaceB)GenerateFaceContacts(b,a,sat.AxisB,-sat.Normal,false,out);else GenerateEdgeContact(a,b,sat,out);if(out.PointCount==0){ContactPoint p{};p.Position=(a.Support(sat.Normal)+b.Support(-sat.Normal))*.5f;p.Penetration=sat.Penetration;out.AddPoint(p);}return true;}
} // namespace Raven::ph
