#include <algorithm>
#include <cstdint>
#include <iomanip>
#include <sstream>
#include <string>
#include <vector>
#include <glad/glad.h>
#include "Raven/Core/Input.h"
#include "Raven/Core/KeyCodes.h"
#include "Raven/Physics/Collision/DynamicAABBTreeValidation.h"
#include "Raven/Physics/Debug/PhysicsDebugOverlayFont.h"
#include "Raven/Physics/Debug/PhysicsDebugRenderer.h"
#include "Raven/Physics/PhysicsWorld.h"
#include "Raven/Renderer/Buffer/IndexBuffer.h"
#include "Raven/Renderer/Buffer/VertexArray.h"
#include "Raven/Renderer/Buffer/VertexBuffer.h"
#include "Raven/Renderer/Material/Material.h"
#include "Raven/Renderer/Mesh/Mesh.h"
#include "Raven/Renderer/Pipeline/Pipeline.h"
#include "Raven/Renderer/Renderer.h"
#include "Raven/Renderer/Shader/Shader.h"
#include "Raven/Scene/Scene.h"

namespace Raven::ph
{
namespace { std::string OnOff(bool e){return e?"ON":"OFF";} std::string FormatFloat(float v){std::ostringstream s;s<<std::fixed<<std::setprecision(3)<<v;return s.str();} }
PhysicsDebugRenderer::PhysicsDebugRenderer(Scene&s,const math::Mat4&v,const math::Mat4&p):m_Scene(&s),m_View(&v),m_Projection(&p){Registry().push_back(this);} PhysicsDebugRenderer::~PhysicsDebugRenderer(){auto&r=Registry();r.erase(std::remove(r.begin(),r.end(),this),r.end());}
void PhysicsDebugRenderer::RenderRegistered(){for(auto*r:Registry())if(r)r->Render();} void PhysicsDebugRenderer::BindPhysicsWorld(Scene&s,const PhysicsWorld&w){for(auto*r:Registry())if(r&&r->m_Scene==&s)r->m_PhysicsWorld=&w;} std::vector<PhysicsDebugRenderer*>& PhysicsDebugRenderer::Registry(){static std::vector<PhysicsDebugRenderer*>r;return r;}
void PhysicsDebugRenderer::EnsureInitialized(){if(m_Material)return;Ref<Shader>shader=Shader::Create("Raven/Assets/Shaders/Vertex/test.vert","Raven/Assets/Shaders/Fragment/test.frag");if(!shader)return;PipelineSpecification sp{};sp.DebugName="Physics Debug Pipeline";sp.Shader=shader;sp.Topology=PrimitiveTopology::Lines;sp.Cull=CullMode::None;sp.DepthTest=false;sp.DepthWrite=false;sp.DepthCompare=DepthCompareOperator::LessEqual;sp.Blend=true;m_Material=CreateRef<Material>(Pipeline::Create(sp));}
void PhysicsDebugRenderer::UpdateToggleKeys(){auto toggle=[](int key,bool&value,bool&was){const bool p=Input::IsKeyPressed(key);if(p&&!was)value=!value;was=p;};toggle(Key::H,m_Settings.ShowSolverStatistics,m_WasOverlayKeyPressed);toggle(Key::B,m_Settings.ShowAABB,m_WasAABBKeyPressed);toggle(Key::O,m_Settings.ShowOBB,m_WasOBBKeyPressed);toggle(Key::F,m_Settings.ShowFatAABB,m_WasFatAABBKeyPressed);toggle(Key::T,m_Settings.ShowDynamicAABBTree,m_WasTreeKeyPressed);toggle(Key::P,m_Settings.ShowBroadPhasePairs,m_WasPairKeyPressed);toggle(Key::C,m_Settings.ShowContactPoints,m_WasContactPointKeyPressed);toggle(Key::N,m_Settings.ShowContactNormals,m_WasContactNormalKeyPressed);}
void PhysicsDebugRenderer::Render(){UpdateToggleKeys();if(!m_Scene||!m_View||!m_Projection)return;const bool world=m_Settings.ShowAABB||m_Settings.ShowOBB||m_Settings.ShowFatAABB||m_Settings.ShowDynamicAABBTree||m_Settings.ShowBroadPhasePairs||m_Settings.ShowContactPoints||m_Settings.ShowContactNormals;if(!world&&!m_Settings.ShowSolverStatistics)return;EnsureInitialized();if(!m_Material)return;if(world)RenderWorldDebug();if(m_Settings.ShowSolverStatistics)RenderOverlay();}
void PhysicsDebugRenderer::RenderWorldDebug(){std::vector<DebugVertex>v;std::vector<uint32_t>i;if(m_Settings.ShowAABB){const math::Vec3 color{.15f,.95f,1};for(auto[e,t,c]:m_Scene->View<TransformComponent,ColliderComponent>()){static_cast<void>(e);AABB b{};if(ComputeColliderAABB(t,c,b))AddAABB(v,i,b,color);}}
if(m_Settings.ShowOBB){const math::Vec3 color{1.0f,.25f,.85f};for(auto[e,t,c]:m_Scene->View<TransformComponent,ColliderComponent>()){static_cast<void>(e);if(c.Type!=ColliderType::Box)continue;OBB b{};if(ComputeBoxOBB(t,c,b))AddOBB(v,i,b,color);}}
if(m_PhysicsWorld){if(m_Settings.ShowFatAABB||m_Settings.ShowDynamicAABBTree){const DynamicAABBTree&tree=m_PhysicsWorld->GetBroadPhase().GetTree();const auto&nodes=tree.GetNodes();const bool valid=ValidateDynamicAABBTree(tree).IsValid();for(const auto&n:nodes){if(n.Height<0)continue;if(n.IsLeaf()){if(m_Settings.ShowFatAABB)AddAABB(v,i,n.Bounds,valid?math::Vec3{.25f,1,.25f}:math::Vec3{1,.15f,.15f});}else if(m_Settings.ShowDynamicAABBTree){float h=std::min(float(n.Height)/8.0f,1.0f);AddAABB(v,i,n.Bounds,valid?math::Vec3{.45f+.45f*h,.25f,1-.35f*h}:math::Vec3{1,.15f,.15f});}}}
if(m_Settings.ShowContactPoints||m_Settings.ShowContactNormals){for(const auto&m:m_PhysicsWorld->GetContactManifolds())for(std::size_t x=0;x<m.PointCount;++x){const auto&p=m.Points[x];if(m_Settings.ShowContactPoints)AddPointMarker(v,i,p.Position,m_Settings.ContactPointRadius,{1,.2f,.2f});if(m_Settings.ShowContactNormals)AddLine(v,i,p.Position,p.Position+m.Normal*m_Settings.ContactNormalLength,{1,1,.2f});}}
if(m_Settings.ShowBroadPhasePairs){for(const auto&p:m_PhysicsWorld->GetBroadPhasePairs()){auto*ta=m_Scene->TryGetComponent<TransformComponent>(p.A.GetIndex());auto*tb=m_Scene->TryGetComponent<TransformComponent>(p.B.GetIndex());auto*ca=m_Scene->TryGetComponent<ColliderComponent>(p.A.GetIndex());auto*cb=m_Scene->TryGetComponent<ColliderComponent>(p.B.GetIndex());if(!ta||!tb||!ca||!cb)continue;AABB a{},b{};if(ComputeColliderAABB(*ta,*ca,a)&&ComputeColliderAABB(*tb,*cb,b))AddLine(v,i,a.GetCenter(),b.GetCenter(),{1,.65f,.1f});}}}SubmitLines(v,i,*m_View,*m_Projection);}
void PhysicsDebugRenderer::RenderOverlay(){if(!m_PhysicsWorld)return;GLint vp[4]={};glGetIntegerv(GL_VIEWPORT,vp);if(vp[2]<=0||vp[3]<=0)return;std::vector<DebugVertex>v;std::vector<uint32_t>i;const auto&s=m_PhysicsWorld->GetSolverDebugStatistics();const math::Vec3 title{.25f,1,.85f},text{.92f,.92f,.92f},on{.35f,1,.35f},off{.65f,.65f,.65f};float y=16;auto add=[&](const std::string&t,const math::Vec3&c){AddOverlayText(v,i,t,16,y,2,vp[2],vp[3],c);y+=18;};add("PHYSICS DEBUG",title);add("[H] HIDE OVERLAY",off);y+=6;add("SOLVER",title);add("MANIFOLDS: "+std::to_string(s.ManifoldCount),text);add("CONTACT POINTS: "+std::to_string(s.ContactPointCount),text);add("PERSISTENT MANIFOLDS: "+std::to_string(s.PersistentManifoldCount),text);add("PERSISTENT CONTACTS: "+std::to_string(s.PersistentContactPointCount),text);add("WARM STARTED: "+std::to_string(s.WarmStartedConstraintCount),text);add("ITERATIONS: "+std::to_string(s.VelocityIterations),text);add("MAX PENETRATION: "+FormatFloat(s.MaxPenetration),text);add("NORMAL IMPULSE: "+FormatFloat(s.MaxNormalImpulse),text);add("FRICTION IMPULSE: "+FormatFloat(s.MaxFrictionImpulse),text);y+=6;add("VISUALIZATION",title);auto tog=[&](const char*k,const char*l,bool e){add(std::string("[")+k+"] "+l+": "+OnOff(e),e?on:off);};tog("B","AABB",m_Settings.ShowAABB);tog("O","OBB",m_Settings.ShowOBB);tog("F","FAT AABB",m_Settings.ShowFatAABB);tog("T","DYNAMIC TREE",m_Settings.ShowDynamicAABBTree);tog("P","BROAD PAIRS",m_Settings.ShowBroadPhasePairs);tog("C","CONTACT POINT",m_Settings.ShowContactPoints);tog("N","CONTACT NORMAL",m_Settings.ShowContactNormals);SubmitLines(v,i,math::Mat4::Identity(),math::Mat4::Identity());}
void PhysicsDebugRenderer::SubmitLines(std::vector<DebugVertex>&v,std::vector<uint32_t>&i,const math::Mat4&view,const math::Mat4&proj){if(v.empty()||i.empty())return;Ref<VertexArray>vao=VertexArray::Create();Ref<VertexBuffer>vbo=VertexBuffer::Create(reinterpret_cast<float*>(v.data()),uint32_t(v.size()*sizeof(DebugVertex)));vbo->SetLayout({{ShaderDataType::Float3,"a_Position"},{ShaderDataType::Float3,"a_Color"},{ShaderDataType::Float2,"a_Texcord"}});vao->AddVertexBuffer(vbo);vao->SetIndexBuffer(IndexBuffer::Create(i.data(),uint32_t(i.size())));Ref<Mesh>mesh=CreateRef<Mesh>(vao,int32_t(i.size()));m_Material->SetUniform("u_View",view);m_Material->SetUniform("u_Projection",proj);m_Material->SetUniform("u_Tint",math::Vec3{1,1,1});m_Material->SetUniform("u_Alpha",1.0f);Renderer::Draw(mesh,m_Material,math::Mat4::Identity());}
void PhysicsDebugRenderer::AddLine(std::vector<DebugVertex>&v,std::vector<uint32_t>&i,const math::Vec3&a,const math::Vec3&b,const math::Vec3&c){uint32_t base=uint32_t(v.size());v.push_back({a,c,{}});v.push_back({b,c,{}});i.push_back(base);i.push_back(base+1);}
void PhysicsDebugRenderer::AddAABB(std::vector<DebugVertex>&v,std::vector<uint32_t>&i,const AABB&b,const math::Vec3&color){const math::Vec3 c[8]={{b.Min.x,b.Min.y,b.Min.z},{b.Max.x,b.Min.y,b.Min.z},{b.Max.x,b.Min.y,b.Max.z},{b.Min.x,b.Min.y,b.Max.z},{b.Min.x,b.Max.y,b.Min.z},{b.Max.x,b.Max.y,b.Min.z},{b.Max.x,b.Max.y,b.Max.z},{b.Min.x,b.Max.y,b.Max.z}};const uint32_t e[12][2]={{0,1},{1,2},{2,3},{3,0},{4,5},{5,6},{6,7},{7,4},{0,4},{1,5},{2,6},{3,7}};for(auto&x:e)AddLine(v,i,c[x[0]],c[x[1]],color);}
void PhysicsDebugRenderer::AddOBB(std::vector<DebugVertex>&v,std::vector<uint32_t>&i,const OBB&b,const math::Vec3&color){math::Vec3 c[8];int n=0;for(int y=-1;y<=1;y+=2)for(int z=-1;z<=1;z+=2)for(int x=-1;x<=1;x+=2)c[n++]=b.Center+b.Axis[0]*(b.HalfExtents.x*float(x))+b.Axis[1]*(b.HalfExtents.y*float(y))+b.Axis[2]*(b.HalfExtents.z*float(z));const uint32_t e[12][2]={{0,1},{0,2},{0,4},{1,3},{1,5},{2,3},{2,6},{3,7},{4,5},{4,6},{5,7},{6,7}};for(auto&x:e)AddLine(v,i,c[x[0]],c[x[1]],color);}
void PhysicsDebugRenderer::AddPointMarker(std::vector<DebugVertex>&v,std::vector<uint32_t>&i,const math::Vec3&p,float radius,const math::Vec3&c){float r=std::max(radius,0.0f);AddLine(v,i,p-math::Vec3{r,0,0},p+math::Vec3{r,0,0},c);AddLine(v,i,p-math::Vec3{0,r,0},p+math::Vec3{0,r,0},c);AddLine(v,i,p-math::Vec3{0,0,r},p+math::Vec3{0,0,r},c);}
void PhysicsDebugRenderer::AddOverlayText(std::vector<DebugVertex>&v,std::vector<uint32_t>&i,const std::string&text,float px,float py,float scale,int w,int h,const math::Vec3&color){if(w<=0||h<=0||scale<=0)return;auto ndc=[&](float x,float y){return math::Vec3{(x/float(w))*2-1,1-(y/float(h))*2,0};};float cursor=px;for(char ch:text){auto glyph=detail::GetPhysicsDebugGlyph(ch);for(int row=0;row<7;++row){int col=0;while(col<5){uint8_t mask=uint8_t(1u<<(4-col));if((glyph[row]&mask)==0){++col;continue;}int start=col;while(col<5&&(glyph[row]&uint8_t(1u<<(4-col))))++col;AddLine(v,i,ndc(cursor+float(start)*scale,py+float(row)*scale),ndc(cursor+float(col)*scale,py+float(row)*scale),color);}}cursor+=6*scale;}}
} // namespace Raven::ph
